"""empty message

Revision ID: 1671e78f512d
Revises: 542286db8e0e
Create Date: 2019-07-25 22:50:39.752479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1671e78f512d'
down_revision = '542286db8e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending', 'password')
    # ### end Alembic commands ###
