"""empty message

Revision ID: 24c9e064da49
Revises: 89434ff16397
Create Date: 2019-07-26 15:07:24.089877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c9e064da49'
down_revision = '89434ff16397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('id_image_name', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'id_image_name')
    # ### end Alembic commands ###
