"""empty message

Revision ID: 7bea1052d48e
Revises: 24c9e064da49
Create Date: 2019-07-26 20:07:32.207455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bea1052d48e'
down_revision = '24c9e064da49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'phone')
    # ### end Alembic commands ###
