"""empty message

Revision ID: 89434ff16397
Revises: ab6e9ef6608f
Create Date: 2019-07-26 10:29:38.686491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89434ff16397'
down_revision = 'ab6e9ef6608f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('photo_name', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'photo_name')
    # ### end Alembic commands ###
