"""empty message

Revision ID: cef9b58e6c9e
Revises: cc90aca46245
Create Date: 2019-08-30 11:42:06.860799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef9b58e6c9e'
down_revision = 'cc90aca46245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_sets',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('face_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['face_id'], ['face.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_sets')
    # ### end Alembic commands ###
