"""empty message

Revision ID: f7975a98d5f9
Revises: debb5fa0f8b9
Create Date: 2019-08-09 22:16:26.003225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7975a98d5f9'
down_revision = 'debb5fa0f8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_name', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_face_data',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('face_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['face_data_id'], ['face_data.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_face_data')
    op.drop_table('face_data')
    # ### end Alembic commands ###
